language: elm
elm:
  - latest-0.19.1
elm_test: 0.19.1
elm_format: 0.8.2

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.elm
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  - npm run test-format
  - npm run test
  - npm run serve &
  - npm run e2e
  - kill $(jobs -p) || true
  - npm run build-gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: release
  on:
    branch: master
